package eg.iti.et3am.model;
// Generated May 16, 2019 11:54:55 PM by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import org.codehaus.jackson.annotate.JsonIgnore;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.GenericGenerator;

/**
 * Coupons generated by hbm2java
 */
@Entity
@Table(name = "coupons", catalog = "heroku_24f192cc0bbf6af",
        uniqueConstraints = @UniqueConstraint(columnNames = "coupon_barcode"))
public class Coupons implements Serializable, Cloneable {

    @Id
    @GeneratedValue(generator = "uuid")
    @GenericGenerator(name = "uuid", strategy = "uuid2")
    @Column(name = "coupon_id", unique = true, nullable = false, length = 128)
    private String couponId;
    @JsonIgnore
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "donator_id", nullable = false)
    private Users users;
    @Column(name = "coupon_value")
    private double couponValue;
    @Column(name = "coupon_barcode", unique = true, nullable = false, length = 45)
    private String couponBarcode;
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "creation_date", length = 26)
    @CreationTimestamp
    private Date creationDate;
    @Column(name = "coupon_qrcode", length = 45)
    @JsonIgnore
    private String couponQrcode;
    @Column(name = "in_balance", nullable = false)
    private int isBalance;
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "coupons")
    @JsonIgnore
    private Set<AvailableCoupons> availableCouponses = new HashSet<>(0);
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "coupons")
    @JsonIgnore
    private Set<UserReserveCoupon> userReserveCoupons = new HashSet<>(0);

    public Coupons() {
    }

    public Coupons(String couponId, Users users, double couponValue, String couponBarcode) {
        this.couponId = couponId;
        this.users = users;
        this.couponValue = couponValue;
        this.couponBarcode = couponBarcode;
    }

    public Coupons(String couponId, Users users, double couponValue, String couponBarcode, Date creationDate, String couponQrcode, Set<AvailableCoupons> availableCouponses, Set<UserReserveCoupon> userReserveCoupons) {
        this.couponId = couponId;
        this.users = users;
        this.couponValue = couponValue;
        this.couponBarcode = couponBarcode;
        this.creationDate = creationDate;
        this.couponQrcode = couponQrcode;
        this.availableCouponses = availableCouponses;
        this.userReserveCoupons = userReserveCoupons;
    }

    
    public String getCouponId() {
        return this.couponId;
    }

    public void setCouponId(String couponId) {
        this.couponId = couponId;
    }

    public Users getUsers() {
        return this.users;
    }

    public void setUsers(Users users) {
        this.users = users;
    }

    public double getCouponValue() {
        return this.couponValue;
    }

    public void setCouponValue(double couponValue) {
        this.couponValue = couponValue;
    }

    public String getCouponBarcode() {
        return this.couponBarcode;
    }

    public void setCouponBarcode(String couponBarcode) {
        this.couponBarcode = couponBarcode;
    }

    public Date getCreationDate() {
        return this.creationDate;
    }

    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    public String getCouponQrcode() {
        return this.couponQrcode;
    }

    public void setCouponQrcode(String couponQrcode) {
        this.couponQrcode = couponQrcode;
    }

    public Set<AvailableCoupons> getAvailableCouponses() {
        return this.availableCouponses;
    }

    public void setAvailableCouponses(Set<AvailableCoupons> availableCouponses) {
        this.availableCouponses = availableCouponses;
    }

    
    public Set<UserReserveCoupon> getUserReserveCoupons() {
        return this.userReserveCoupons;
    }

    public void setUserReserveCoupons(Set<UserReserveCoupon> userReserveCoupons) {
        this.userReserveCoupons = userReserveCoupons;
    }

    public int getIsBalance() {
        return isBalance;
    }

    public void setIsBalance(int isBalance) {
        this.isBalance = isBalance;
    }

    @Override
    public Object clone() throws CloneNotSupportedException {
        return super.clone();
    }
}
