package eg.iti.et3am.model;
// Generated Jul 1, 2019 2:47:04 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Inquiries generated by hbm2java
 */
@Entity
@Table(name="inquiries"
    ,catalog="heroku_24f192cc0bbf6af"
)
public class Inquiries  implements java.io.Serializable {


     private Integer idInquiries;
     private Users users;
     private Integer status;
     private Date creationDate;
     private String title;
     private String message;

    public Inquiries() {
    }

	
    public Inquiries(Users users, Date creationDate) {
        this.users = users;
        this.creationDate = creationDate;
    }
    public Inquiries(Users users, Integer status, Date creationDate, String title, String message) {
       this.users = users;
       this.status = status;
       this.creationDate = creationDate;
       this.title = title;
       this.message = message;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_inquiries", unique=true, nullable=false)
    public Integer getIdInquiries() {
        return this.idInquiries;
    }
    
    public void setIdInquiries(Integer idInquiries) {
        this.idInquiries = idInquiries;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="sender_id", nullable=false)
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

    
    @Column(name="status")
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="creation_date", nullable=false, length=26)
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    
    @Column(name="title", length=128)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    
    @Column(name="message", length=1024)
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }




}


