package eg.iti.et3am.model;
// Generated May 16, 2019 11:54:55 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.codehaus.jackson.annotate.JsonIgnore;

/**
 * Meals generated by hbm2java
 */
@Entity
@Table(name = "meals", catalog = "heroku_24f192cc0bbf6af")
public class Meals implements java.io.Serializable {

    private Integer mealId;
    private Restaurants restaurants;
    private String mealName;
    private float mealValue;
    private String mealImage;

    public Meals() {
    }

    public Meals(Restaurants restaurants, String mealName, float mealValue) {
        this.restaurants = restaurants;
        this.mealName = mealName;
        this.mealValue = mealValue;
    }

    public Meals(Restaurants restaurants, String mealName, float mealValue, String mealImage) {
        this.restaurants = restaurants;
        this.mealName = mealName;
        this.mealValue = mealValue;
        this.mealImage = mealImage;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "meal_id", unique = true, nullable = false)
    public Integer getMealId() {
        return this.mealId;
    }

    public void setMealId(Integer mealId) {
        this.mealId = mealId;
    }

    @JsonIgnore
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "resturant_id", nullable = false)
    public Restaurants getRestaurants() {
        return this.restaurants;
    }

    public void setRestaurants(Restaurants restaurants) {
        this.restaurants = restaurants;
    }

    @Column(name = "meal_name", nullable = false, length = 45)
    public String getMealName() {
        return this.mealName;
    }

    public void setMealName(String mealName) {
        this.mealName = mealName;
    }

    @Column(name = "meal_value", nullable = false, precision = 12, scale = 0)
    public float getMealValue() {
        return this.mealValue;
    }

    public void setMealValue(float mealValue) {
        this.mealValue = mealValue;
    }

    @Column(name = "meal_image", length = 45)
    public String getMealImage() {
        return this.mealImage;
    }

    public void setMealImage(String mealImage) {
        this.mealImage = mealImage;
    }
}
