package eg.iti.et3am.model;
// Generated Jul 4, 2019 9:55:21 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Meals generated by hbm2java
 */
@Entity
@Table(name="meals"
    ,catalog="heroku_24f192cc0bbf6af"
)
public class Meals  implements java.io.Serializable {


     private Integer mealId;
     private Restaurants restaurants;
     private String mealName;
     private float mealValue;
     private String mealImage;
     private Set<UserUsedCoupon> userUsedCoupons = new HashSet<UserUsedCoupon>(0);

    public Meals() {
    }

	
    public Meals(Restaurants restaurants, String mealName, float mealValue) {
        this.restaurants = restaurants;
        this.mealName = mealName;
        this.mealValue = mealValue;
    }
    public Meals(Restaurants restaurants, String mealName, float mealValue, String mealImage, Set<UserUsedCoupon> userUsedCoupons) {
       this.restaurants = restaurants;
       this.mealName = mealName;
       this.mealValue = mealValue;
       this.mealImage = mealImage;
       this.userUsedCoupons = userUsedCoupons;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="meal_id", unique=true, nullable=false)
    public Integer getMealId() {
        return this.mealId;
    }
    
    public void setMealId(Integer mealId) {
        this.mealId = mealId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="resturant_id", nullable=false)
    public Restaurants getRestaurants() {
        return this.restaurants;
    }
    
    public void setRestaurants(Restaurants restaurants) {
        this.restaurants = restaurants;
    }

    
    @Column(name="meal_name", nullable=false, length=45)
    public String getMealName() {
        return this.mealName;
    }
    
    public void setMealName(String mealName) {
        this.mealName = mealName;
    }

    
    @Column(name="meal_value", nullable=false, precision=12, scale=0)
    public float getMealValue() {
        return this.mealValue;
    }
    
    public void setMealValue(float mealValue) {
        this.mealValue = mealValue;
    }

    
    @Column(name="meal_image", length=45)
    public String getMealImage() {
        return this.mealImage;
    }
    
    public void setMealImage(String mealImage) {
        this.mealImage = mealImage;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="meals")
    public Set<UserUsedCoupon> getUserUsedCoupons() {
        return this.userUsedCoupons;
    }
    
    public void setUserUsedCoupons(Set<UserUsedCoupon> userUsedCoupons) {
        this.userUsedCoupons = userUsedCoupons;
    }




}


