package eg.iti.et3am.model;
// Generated May 15, 2019 11:40:21 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * RestaurantAdmin generated by hbm2java
 */
@Entity
@Table(name="restaurant_admin"
    ,catalog="heroku_24f192cc0bbf6af"
    , uniqueConstraints = @UniqueConstraint(columnNames="restaurant_admin_email") 
)
public class RestaurantAdmin  implements java.io.Serializable {


     private RestaurantAdminId id;
     private Restaurants restaurants;
     private String restaurantAdminEmail;
     private String restaurantAdminPassword;

    public RestaurantAdmin() {
    }

    public RestaurantAdmin(RestaurantAdminId id, Restaurants restaurants, String restaurantAdminEmail, String restaurantAdminPassword) {
       this.id = id;
       this.restaurants = restaurants;
       this.restaurantAdminEmail = restaurantAdminEmail;
       this.restaurantAdminPassword = restaurantAdminPassword;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="restaurantAdminId", column=@Column(name="restaurant_admin_id", nullable=false) ), 
        @AttributeOverride(name="restaurantsRestaurantId", column=@Column(name="restaurants_restaurant_id", nullable=false) ) } )
    public RestaurantAdminId getId() {
        return this.id;
    }
    
    public void setId(RestaurantAdminId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="restaurants_restaurant_id", nullable=false, insertable=false, updatable=false)
    public Restaurants getRestaurants() {
        return this.restaurants;
    }
    
    public void setRestaurants(Restaurants restaurants) {
        this.restaurants = restaurants;
    }

    
    @Column(name="restaurant_admin_email", unique=true, nullable=false, length=45)
    public String getRestaurantAdminEmail() {
        return this.restaurantAdminEmail;
    }
    
    public void setRestaurantAdminEmail(String restaurantAdminEmail) {
        this.restaurantAdminEmail = restaurantAdminEmail;
    }

    
    @Column(name="restaurant_admin_password", nullable=false, length=45)
    public String getRestaurantAdminPassword() {
        return this.restaurantAdminPassword;
    }
    
    public void setRestaurantAdminPassword(String restaurantAdminPassword) {
        this.restaurantAdminPassword = restaurantAdminPassword;
    }




}


