package eg.iti.et3am.model;
// Generated May 16, 2019 11:54:55 PM by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;
import org.codehaus.jackson.annotate.JsonIgnore;

/**
 * Restaurants generated by hbm2java
 */
@Entity
@Table(name = "restaurants", catalog = "heroku_24f192cc0bbf6af")
public class Restaurants implements Serializable, Cloneable, Comparable<Restaurants> {

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "restaurant_id", unique = true, nullable = false)
    private Integer restaurantId;
    @Column(name = "restaurant_name", nullable = false, length = 45)
    private String restaurantName;
    @Column(name = "city", nullable = false, length = 45)
    private String city;
    @Column(name = "country", nullable = false, length = 45)
    private String country;
    @Column(name = "latitude", nullable = false, precision = 12, scale = 0)
    private double latitude;
    @Column(name = "longitude", nullable = false, precision = 12, scale = 0)
    private double longitude;
    @Transient
    private double distance;
    @Column(name = "restaurant_image", length = 45)
    private String restaurantImage;
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "restaurants")
    private Set<RestaurantAdmin> restaurantAdmins = new HashSet<>(0);
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "restaurants")
    private Set<Meals> mealses = new HashSet<>(0);
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "restaurants")
    private Set<UserUsedCoupon> userUsedCoupons = new HashSet<>(0);

    public Restaurants() {
    }

    public Restaurants(String restaurantName, String city, String country, double latitude, double longitude) {
        this.restaurantName = restaurantName;
        this.city = city;
        this.country = country;
        this.latitude = latitude;
        this.longitude = longitude;
    }

    public Restaurants(String restaurantName, String city, String country, double latitude, double longitude, String restaurantImage, Set<RestaurantAdmin> restaurantAdmins, Set<Meals> mealses, Set<UserUsedCoupon> userUsedCoupons) {
        this.restaurantName = restaurantName;
        this.city = city;
        this.country = country;
        this.latitude = latitude;
        this.longitude = longitude;
        this.restaurantImage = restaurantImage;
        this.restaurantAdmins = restaurantAdmins;
        this.mealses = mealses;
        this.userUsedCoupons = userUsedCoupons;
    }

    public Integer getRestaurantId() {
        return this.restaurantId;
    }

    public void setRestaurantId(Integer restaurantId) {
        this.restaurantId = restaurantId;
    }

    public String getRestaurantName() {
        return this.restaurantName;
    }

    public void setRestaurantName(String restaurantName) {
        this.restaurantName = restaurantName;
    }

    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getCountry() {
        return this.country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public double getLatitude() {
        return this.latitude;
    }

    public void setLatitude(double latitude) {
        this.latitude = latitude;
    }

    public double getLongitude() {
        return this.longitude;
    }

    public void setLongitude(double longitude) {
        this.longitude = longitude;
    }

    public double getDistance() {
        return distance;
    }

    public void setDistance(double distance) {
        this.distance = distance;
    }

    public String getRestaurantImage() {
        return this.restaurantImage;
    }

    public void setRestaurantImage(String restaurantImage) {
        this.restaurantImage = restaurantImage;
    }

    @JsonIgnore
    public Set<RestaurantAdmin> getRestaurantAdmins() {
        return this.restaurantAdmins;
    }

    public void setRestaurantAdmins(Set<RestaurantAdmin> restaurantAdmins) {
        this.restaurantAdmins = restaurantAdmins;
    }

    @JsonIgnore //if uncomment this will retrive meals:[]
    public Set<Meals> getMealses() {
        return this.mealses;
    }

    public void setMealses(Set<Meals> mealses) {
        this.mealses = mealses;
    }

    @JsonIgnore
    public Set<UserUsedCoupon> getUserUsedCoupons() {
        return this.userUsedCoupons;
    }

    public void setUserUsedCoupons(Set<UserUsedCoupon> userUsedCoupons) {
        this.userUsedCoupons = userUsedCoupons;
    }

    @Override
    public Object clone() throws CloneNotSupportedException {
        return super.clone();
    }

    @Override
    public int compareTo(Restaurants o) {
        return new Double(getLatitude()).compareTo(o.getLatitude());
    }

}
