package eg.iti.et3am.model;
// Generated May 16, 2019 11:54:55 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RestaurantAdminId generated by hbm2java
 */
@Embeddable
public class RestaurantAdminId  implements java.io.Serializable {


     private int restaurantAdminId;
     private int restaurantsRestaurantId;

    public RestaurantAdminId() {
    }

    public RestaurantAdminId(int restaurantAdminId, int restaurantsRestaurantId) {
       this.restaurantAdminId = restaurantAdminId;
       this.restaurantsRestaurantId = restaurantsRestaurantId;
    }
   


    @Column(name="restaurant_admin_id", nullable=false)
    public int getRestaurantAdminId() {
        return this.restaurantAdminId;
    }
    
    public void setRestaurantAdminId(int restaurantAdminId) {
        this.restaurantAdminId = restaurantAdminId;
    }


    @Column(name="restaurants_restaurant_id", nullable=false)
    public int getRestaurantsRestaurantId() {
        return this.restaurantsRestaurantId;
    }
    
    public void setRestaurantsRestaurantId(int restaurantsRestaurantId) {
        this.restaurantsRestaurantId = restaurantsRestaurantId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RestaurantAdminId) ) return false;
		 RestaurantAdminId castOther = ( RestaurantAdminId ) other; 
         
		 return (this.getRestaurantAdminId()==castOther.getRestaurantAdminId())
 && (this.getRestaurantsRestaurantId()==castOther.getRestaurantsRestaurantId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getRestaurantAdminId();
         result = 37 * result + this.getRestaurantsRestaurantId();
         return result;
   }   


}


