package eg.iti.et3am.model;
// Generated Jul 4, 2019 9:55:21 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ThanksMessages generated by hbm2java
 */
@Entity
@Table(name="thanks_messages"
    ,catalog="heroku_24f192cc0bbf6af"
)
public class ThanksMessages  implements java.io.Serializable {


     private Integer idThanksMessages;
     private Integer status;
     private String message;
     private Date creationDate;

    public ThanksMessages() {
    }

	
    public ThanksMessages(Date creationDate) {
        this.creationDate = creationDate;
    }
    public ThanksMessages(Integer status, String message, Date creationDate) {
       this.status = status;
       this.message = message;
       this.creationDate = creationDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_thanks_messages", unique=true, nullable=false)
    public Integer getIdThanksMessages() {
        return this.idThanksMessages;
    }
    
    public void setIdThanksMessages(Integer idThanksMessages) {
        this.idThanksMessages = idThanksMessages;
    }

    
    @Column(name="status")
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }

    
    @Column(name="message", length=1024)
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="creation_date", nullable=false, length=19)
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }




}


