package eg.iti.et3am.model;
// Generated Jul 4, 2019 9:55:21 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserUsedCoupon generated by hbm2java
 */
@Entity
@Table(name = "user_used_coupon",
        catalog = "heroku_24f192cc0bbf6af"
)
public class UserUsedCoupon implements java.io.Serializable, Cloneable {

    private Integer usedCouponId;
    private Meals meals;
    private Restaurants restaurants;
    private UserReserveCoupon userReserveCoupon;
    private Date useDate;
    private float price;
    private int status;
    private Integer messageId;
    private String userUsedCouponcol;
    private Set<RemainingBalance> remainingBalances = new HashSet<>(0);

    public UserUsedCoupon() {
    }

    public UserUsedCoupon(UserReserveCoupon userReserveCoupon, Date useDate, float price, int status) {
        this.userReserveCoupon = userReserveCoupon;
        this.useDate = useDate;
        this.price = price;
        this.status = status;
    }

    public UserUsedCoupon(Meals meals, Restaurants restaurants, UserReserveCoupon userReserveCoupon, Date useDate, float price, int status, Integer messageId, String userUsedCouponcol, Set<RemainingBalance> remainingBalances) {
        this.meals = meals;
        this.restaurants = restaurants;
        this.userReserveCoupon = userReserveCoupon;
        this.useDate = useDate;
        this.price = price;
        this.status = status;
        this.messageId = messageId;
        this.userUsedCouponcol = userUsedCouponcol;
        this.remainingBalances = remainingBalances;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "used_coupon_id", unique = true, nullable = false)
    public Integer getUsedCouponId() {
        return this.usedCouponId;
    }

    public void setUsedCouponId(Integer usedCouponId) {
        this.usedCouponId = usedCouponId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "meal_id")
    public Meals getMeals() {
        return this.meals;
    }

    public void setMeals(Meals meals) {
        this.meals = meals;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "restaurant_id")
    public Restaurants getRestaurants() {
        return this.restaurants;
    }

    public void setRestaurants(Restaurants restaurants) {
        this.restaurants = restaurants;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_reserve_coupon_reserved_coupon_id", nullable = false)
    public UserReserveCoupon getUserReserveCoupon() {
        return this.userReserveCoupon;
    }

    public void setUserReserveCoupon(UserReserveCoupon userReserveCoupon) {
        this.userReserveCoupon = userReserveCoupon;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "use_date", nullable = false, length = 19)
    public Date getUseDate() {
        return this.useDate;
    }

    public void setUseDate(Date useDate) {
        this.useDate = useDate;
    }

    @Column(name = "price", nullable = false, precision = 12, scale = 0)
    public float getPrice() {
        return this.price;
    }

    public void setPrice(float price) {
        this.price = price;
    }

    @Column(name = "status", nullable = false)
    public int getStatus() {
        return this.status;
    }

    public void setStatus(int status) {
        this.status = status;
    }

    @Column(name = "message_id")
    public Integer getMessageId() {
        return this.messageId;
    }

    public void setMessageId(Integer messageId) {
        this.messageId = messageId;
    }

    @Column(name = "user_used_couponcol", length = 45)
    public String getUserUsedCouponcol() {
        return this.userUsedCouponcol;
    }

    public void setUserUsedCouponcol(String userUsedCouponcol) {
        this.userUsedCouponcol = userUsedCouponcol;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "userUsedCoupon")
    public Set<RemainingBalance> getRemainingBalances() {
        return this.remainingBalances;
    }

    public void setRemainingBalances(Set<RemainingBalance> remainingBalances) {
        this.remainingBalances = remainingBalances;
    }

    @Override
    public Object clone() throws CloneNotSupportedException {
        return super.clone();
    }
}
