package eg.iti.et3am.model;
// Generated May 16, 2019 11:54:55 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.ColumnDefault;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.GenericGenerator;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name="users"
    ,catalog="heroku_24f192cc0bbf6af"
    , uniqueConstraints = @UniqueConstraint(columnNames="user_email") 
)
public class Users  implements java.io.Serializable {


    @Id
    @GeneratedValue(generator = "uuid")
    @GenericGenerator(name = "uuid", strategy = "uuid2")
    @Column(name="user_id", unique=true, nullable=false, length=128)
     private String userId;
    
    @Column(name="user_name", nullable=false, length=45)
     private String userName;
    
@Column(name="user_email", unique=true, nullable=false, length=45)
     private String userEmail;

@Column(name="password", nullable=false, length=45)
     private String password;

@ColumnDefault("0")
@Column(name="verified", nullable=false)
     private int verified;

//@Temporal(TemporalType.DATE)
@CreationTimestamp
@Temporal(TemporalType.TIMESTAMP)
     @Column(name="creation_date", length=10)
     private Date creationDate;

@ColumnDefault("1")
@Column(name="user_status")
     private Integer userStatus;

@OneToMany(fetch=FetchType.LAZY, mappedBy="users")
     private Set<UserReserveCoupon> userReserveCoupons = new HashSet<UserReserveCoupon>(0);

@OneToMany(fetch=FetchType.LAZY, mappedBy="users")
     private Set<Coupons> couponses = new HashSet<Coupons>(0);

@OneToMany(fetch=FetchType.LAZY, mappedBy="users")
     private Set<UserDetails> userDetailses = new HashSet<UserDetails>(0);

    public Users() {
    }

	
    public Users(String userId, String userName, String userEmail, String password, int verified) {
        this.userId = userId;
        this.userName = userName;
        this.userEmail = userEmail;
        this.password = password;
        this.verified = verified;
    }
    public Users(String userId, String userName, String userEmail, String password, int verified, Date creationDate, Integer userStatus, Set<UserReserveCoupon> userReserveCoupons, Set<Coupons> couponses, Set<UserDetails> userDetailses) {
       this.userId = userId;
       this.userName = userName;
       this.userEmail = userEmail;
       this.password = password;
       this.verified = verified;
       this.creationDate = creationDate;
       this.userStatus = userStatus;
       this.userReserveCoupons = userReserveCoupons;
       this.couponses = couponses;
       this.userDetailses = userDetailses;
    }
   
     
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }

    
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }

    
    public String getUserEmail() {
        return this.userEmail;
    }
    
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }

    
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    public int getVerified() {
        return this.verified;
    }
    
    public void setVerified(int verified) {
        this.verified = verified;
    }

    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    
    public Integer getUserStatus() {
        return this.userStatus;
    }
    
    public void setUserStatus(Integer userStatus) {
        this.userStatus = userStatus;
    }

    public Set<UserReserveCoupon> getUserReserveCoupons() {
        return this.userReserveCoupons;
    }
    
    public void setUserReserveCoupons(Set<UserReserveCoupon> userReserveCoupons) {
        this.userReserveCoupons = userReserveCoupons;
    }

    public Set<Coupons> getCouponses() {
        return this.couponses;
    }
    
    public void setCouponses(Set<Coupons> couponses) {
        this.couponses = couponses;
    }

    public Set<UserDetails> getUserDetailses() {
        return this.userDetailses;
    }
    
    public void setUserDetailses(Set<UserDetails> userDetailses) {
        this.userDetailses = userDetailses;
    }




}


