package eg.iti.et3am.model;
// Generated Jul 4, 2019 9:55:21 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users",
        catalog = "heroku_24f192cc0bbf6af",
        uniqueConstraints = @UniqueConstraint(columnNames = "user_email")
)
public class Users implements java.io.Serializable {

    private String userId;
    private String userName;
    private String userEmail;
    private String password;
    private int verified;
    private Date creationDate;
    private Integer userStatus;
    private Set<Inquiries> inquirieses = new HashSet<>(0);
    private Set<UserReserveCoupon> userReserveCoupons = new HashSet<>(0);
    private Set<Coupons> couponses = new HashSet<>(0);
    private Set<UserDetails> userDetailses = new HashSet<>(0);

    public Users() {
    }

    public Users(String userId, String userName, String userEmail, String password, int verified) {
        this.userId = userId;
        this.userName = userName;
        this.userEmail = userEmail;
        this.password = password;
        this.verified = verified;
    }

    public Users(String userId, String userName, String userEmail, String password, int verified, Date creationDate, Integer userStatus, Set<Inquiries> inquirieses, Set<UserReserveCoupon> userReserveCoupons, Set<Coupons> couponses, Set<UserDetails> userDetailses) {
        this.userId = userId;
        this.userName = userName;
        this.userEmail = userEmail;
        this.password = password;
        this.verified = verified;
        this.creationDate = creationDate;
        this.userStatus = userStatus;
        this.inquirieses = inquirieses;
        this.userReserveCoupons = userReserveCoupons;
        this.couponses = couponses;
        this.userDetailses = userDetailses;
    }

    @Id

    @Column(name = "user_id", unique = true, nullable = false, length = 128)
    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    @Column(name = "user_name", nullable = false, length = 45)
    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    @Column(name = "user_email", unique = true, nullable = false, length = 45)
    public String getUserEmail() {
        return this.userEmail;
    }

    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }

    @Column(name = "password", nullable = false, length = 45)
    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @Column(name = "verified", nullable = false)
    public int getVerified() {
        return this.verified;
    }

    public void setVerified(int verified) {
        this.verified = verified;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "creation_date", length = 10)
    public Date getCreationDate() {
        return this.creationDate;
    }

    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    @Column(name = "user_status")
    public Integer getUserStatus() {
        return this.userStatus;
    }

    public void setUserStatus(Integer userStatus) {
        this.userStatus = userStatus;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
    public Set<Inquiries> getInquirieses() {
        return this.inquirieses;
    }

    public void setInquirieses(Set<Inquiries> inquirieses) {
        this.inquirieses = inquirieses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
    public Set<UserReserveCoupon> getUserReserveCoupons() {
        return this.userReserveCoupons;
    }

    public void setUserReserveCoupons(Set<UserReserveCoupon> userReserveCoupons) {
        this.userReserveCoupons = userReserveCoupons;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
    public Set<Coupons> getCouponses() {
        return this.couponses;
    }

    public void setCouponses(Set<Coupons> couponses) {
        this.couponses = couponses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
    public Set<UserDetails> getUserDetailses() {
        return this.userDetailses;
    }

    public void setUserDetailses(Set<UserDetails> userDetailses) {
        this.userDetailses = userDetailses;
    }

}
