package eg.iti.et3am.model;
// Generated May 16, 2019 11:54:55 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UserBalanceCoupon generated by hbm2java
 */
@Entity
@Table(name="user_balance_coupon"
    ,catalog="heroku_24f192cc0bbf6af"
)
public class UserBalanceCoupon  implements java.io.Serializable {


     private Integer balanceId;
     private Users users;
     private int status;
     private Set<Coupons> couponses = new HashSet<Coupons>(0);

    public UserBalanceCoupon() {
    }

	
    public UserBalanceCoupon(Users users, int status) {
        this.users = users;
        this.status = status;
    }
    public UserBalanceCoupon(Users users, int status, Set<Coupons> couponses) {
       this.users = users;
       this.status = status;
       this.couponses = couponses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="balance_id", unique=true, nullable=false)
    public Integer getBalanceId() {
        return this.balanceId;
    }
    
    public void setBalanceId(Integer balanceId) {
        this.balanceId = balanceId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="users_user_id", nullable=false)
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

    
    @Column(name="status", nullable=false)
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="userBalanceCoupon")
    public Set<Coupons> getCouponses() {
        return this.couponses;
    }
    
    public void setCouponses(Set<Coupons> couponses) {
        this.couponses = couponses;
    }




}


