package eg.iti.et3am.model;
// Generated May 14, 2019 1:25:21 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.codehaus.jackson.annotate.JsonIgnoreProperties;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="users"
    ,catalog="et3am"
    , uniqueConstraints = @UniqueConstraint(columnNames="user_email") 
)
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class User  implements java.io.Serializable {


    @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="user_id", unique=true, nullable=false)
     private long userId;
    @Column(name="user_name", nullable=false, length=45)
     private String userName;
@Column(name="user_email", unique=true, nullable=false, length=45)
     private String userEmail;
@Column(name="password", nullable=false, length=45)
     private String password;
@Column(name="verified", nullable=false)
     private int verified;

    public User() {
    }

    public User(String userName, String userEmail, String password) {
        this.userName = userName;
        this.userEmail = userEmail;
        this.password = password;
    }

    public long getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getUserEmail() {
        return userEmail;
    }

    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public int getVerified() {
        return verified;
    }

    public void setVerified(int verified) {
        this.verified = verified;
    }

}


